server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2login?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: shehap


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          github:
            client_id:
            client_secret:
          google:
            client_id:
            client_secret:

