server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2login?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: shehap


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Iv1.a1f5a593c4c5bd8a
            clientSecret: 0e56a3b4456a9b28502056f856442c5f22233aef
          google:
            client_id: 813246067644-edfqvtihc4e9fl6db0b1112qr68eml77.apps.googleusercontent.com
            client_secret: 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

    jwt:
      secret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
      expiration: 20000  # 20 seconds

  app:
    authorized_redirect: http://localhost:3000/oauth2/redirect



